version: '3.8'

services:
  frontend:
    image: frontend-project:v2
    build: .
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/
    ports:
      - 5000:5000
  backend:
    image: backend-project:v2
    build: .
    environment:
      - REDIS_HOST=redis-db
    ports:
      - 8080:8080
  redis-db:
    image: redis
    restart: unless-stopped
